export const navBar = [
  { name: "Home", path: "/" },
  { name: "About", path: "/about" },
  { name: "Contact", path: "/contact" },
  { name: "Projects", path: "/projects" },
];

export const projectsData = [
  {
    id: 1,
    title: "Prosopographic Database of 20th Century Georgia (PDG)",
    cover: "thumbnails/1.png",
    stage: "Production",
    tecnologies: [
      "Bootstrap",
      "Sass",
      "Js",
      "DataTables",
      "Mabbox",
      "Omeka",
      "Neatline",
    ],
    url: "https://prosopography.iliauni.edu.ge/",
    client: "Ilia State University",
  },
  {
    id: 2,
    title:
      "Prosopographic Database of The Society for the Spread of Literacy Among Georgians",
    cover: "thumbnails/2.png",
    stage: "Production",
    tecnologies: [
      "Bootstrap",
      "Sass",
      "Js",
      "DataTables",
      "Mabbox",
      "Gephi",
      "GEXF",
      "visNetwork",
      "ChartJS",
    ],
    url: "https://society.iliauni.edu.ge/",
    client: "Ilia State University",
  },
  {
    id: 3,
    title: "The prosopographic database of Georgian Catholic missions",
    cover: "thumbnails/3.png",
    stage: "Production",
    tecnologies: ["Bootstrap", "Sass", "Js", "jQuery", "Mabbox", "CETEIcean"],
    url: "https://missio.iliauni.edu.ge/ka",
    client: "Ilia State University",
  },
  {
    id: 4,
    title: "Cave Biodiversity of Georgia",
    cover: "thumbnails/4.png",
    stage: "Production",
    tecnologies: [
      "Bootstrap",
      "Sass",
      "Js",
      "DataTables",
      "Mabbox",
      "ChartJS",
      "D3.js",
    ],
    url: "https://cbg.iliauni.edu.ge/en",
    client: "Ilia State University",
  },
  {
    id: 5,
    title:
      "Black Sea Representation in Literary and Historical sources: Virtual Map",
    cover: "thumbnails/5.png",
    stage: "Production",
    tecnologies: [
      "Bootstrap",
      "Sass",
      "Js",
      "DataTables",
      "Mabbox",
      "ChartJS",
      "Doccano",
    ],
    url: "https://bsr.iliauni.edu.ge/ka",
    client: "Ilia State University",
  },
  {
    id: 6,
    title: "Digital Film Catalog of the National Archives of Georgia",
    cover: "thumbnails/6.png",
    stage: "Production",
    tecnologies: ["React", "Sass", "Inertia.js"],
    url: "https://filmcatalog.ge/en",
    client: "Central Archive of Audio-Visual Documents",
  },
  {
    id: 7,
    title: "Authentication form with localStorage",
    cover: "thumbnails/7.png",
    stage: "Practice",
    tecnologies: ["React", "Reactstrap"],
    url: "https://github.com/ratigumashvili/ol-academy-user-authentication-with-ls",
  },
  {
    id: 8,
    title: "Modal",
    cover: "thumbnails/8.png",
    stage: "Practice",
    tecnologies: ["React"],
    url: "https://github.com/ratigumashvili/ol-academy-popup-with-handling-outside-click",
  },
  {
    id: 9,
    title: "Imitated twitter posts",
    cover: "thumbnails/9.png",
    stage: "Practice",
    tecnologies: ["React"],
    url: "https://github.com/ratigumashvili/ol-academy-imitated-twitter-posts",
  },
  {
    id: 10,
    title: "React context menu",
    cover: "thumbnails/10.png",
    stage: "Practice",
    tecnologies: ["React"],
    url: "https://github.com/ratigumashvili/ol-academy-context-menu",
  },
  {
    id: 11,
    title: "React Todo App",
    cover: "thumbnails/11.png",
    stage: "Practice",
    tecnologies: ["React"],
    url: "https://github.com/ratigumashvili/ol-academy-react-todo",
  },
];
